language: python
python:
- 3.7.4
virtualenv:
  system_site_packages: true
install:
- pip install codecov
- pip install pytest-cov
- pip install -r requirements.txt
script:
- pytest
- coverage run -m pytest
after_success:
- codecov
after_script:
- cd /src
deploy:
  provider: pypi
  user: GenesisCoast
after_success:
  - python scripts/increment_version.py