language: python
python:
- 3.7.4
install:
- pip install codecov
- pip install pytest-cov
- pip install -r requirements.txt
script:
- python -m pytest tests/
- coverage run -m pytest
after_success:
- python scripts/increment_version.py
after_script:
- cd /src
deploy:
  provider: pypi
  user: GenesisCoast