trigger: none
# this does h

pool: DA-PBA

test:
  item: test1

list:
- item 1
  # this is for L.

- item 2

parameters:
# The parameters do X.

- name: computeResourceGroupName
  value: rg-ne-compute-001
  # This variable does X
  # and Y.

- name: System.Debug
  value: true
  # Description:
  #   This parameter does A.
  # Name: New

- name: connectedServiceName
  value: rg-ne-compute-001-sc
  # Description:
  #   This does ABC.
  # Example:
  #   rg-ne-compute-001-sc

- name: containerInstanceName
  value: ci-ne-compute-001

steps:
- script: echo "123"
  # Description:
  #   xyz